galaxy_info:
  author: Amirhossein Shaerpour
  description: Setup redis sentinel for High Availability
  license: MIT

  min_ansible_version: 2.1

  galaxy_tags:
    - redis
    - redis-sentinel
    - high-availability
